language: elixir

sudo: false

cache:
  directories:
    - $HOME/.cargo

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup update
  - rustc -Vv
  - cargo -V
  - rustup default nightly
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
  - export RUST_BACKTRACE=1

elixir:
  - 1.0.5
otp_release: 17.4

matrix:
  include:
    - elixir: 1.4.4
      otp_release: 19.3
