[package]
name = "sdr"
version = "0.1.0"
authors = ["Tomas Korcak <korczis@gmail.com>"]

[dependencies]
clap = ">= 2.18"
sdr-hackrf = { path = "../hackrf"}
sdr-rtl = { path = "../rtl"}
sdr-shared = { path = "../sdr-shared"}

[[bin]]
name = "sdr"
path = "src/main.rs"
